default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: wordless-spy       # ← Change if you're using a different DB user
  password: wordless-spy
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: wordless_spy_development

test:
  <<: *default
  database: wordless_spy_test

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: wordless_spy_production

  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: wordless_spy_production

  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: wordless_spy_production

  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    database: wordless_spy_production

